DROP DATABASE IF EXISTS banco_dados; /** ELIMINAR SE EXISTIR **/
CREATE DATABASE banco_dados; /** CRIAR BANCO DE DADOS **/
USE banco_dados; /** SELECIONAR BANCO DE DADOS **/

CREATE TABLE estado(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(255) NOT NULL UNIQUE
,sigla CHAR(2) NOT NULL UNIQUE
,ativo CHAR(1) NOT NULL DEFAULT 'S'
); /** CRIAR TABELA **/

INSERT INTO estado (id,nome,sigla,ativo)
VALUES (NULL,'PARANÁ','PR','S'); /** PRIMEIRA FORMA DE INSERÇÃO **/

INSERT INTO estado
VALUES (NULL, 'SÃO PAULO','SP','S'); /** SEGUNDA FORMA DE INSERÇÃO **/

INSERT INTO estado (nome,sigla)
VALUES ('MATO GROSSO','MT'); /** TERCEIRA FORMA DE INSERÇÃO **/

SELECT * FROM estado;

/** CRIAR A TABELA PRODUTO(ID,NOME,PRECO_CUSTO,PRECO_VENDA,ATIVO) 3 INSERÇÕES E VERIFIQUE **/

CREATE TABLE produto(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(255) NOT NULL UNIQUE
,preco_custo DECIMAL(8,2) NOT NULL
,preco_venda DECIMAL(8,2) NOT NULL
,ativo CHAR(1) NOT NULL DEFAULT 'S'
);

INSERT INTO produto (id,nome,preco_custo,preco_venda,ativo)
VALUES (NULL, 'REFRI',5.00,5.00,'S'); /** PRIMEIRA FORMA DE INSERÇÃO **/

INSERT INTO produto
VALUES (NULL, 'BOLACHA',3.00,3.00,'S'); /** SEGUNDA FORMA DE INSERÇÃO **/

INSERT INTO produto (nome,preco_custo,preco_venda)
VALUES ('MACARRAO',8.00,8.00); /** TERCEIRA FORMA DE INSERÇÃO **/

SELECT * FROM produto;

/** CRIAR TABELA CIDADE COM FOREING KEY PARA ESTADO **/

CREATE TABLE cidade(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(255) NOT NULL UNIQUE
,estado_id INT NOT NULL
,ativo CHAR(1) NOT NULL DEFAULT 'S'
,CHECK (ativo IN('S','N'))
,FOREIGN KEY (estado_id) REFERENCES estado (ID)
);

INSERT INTO cidade(nome,estado_id)
VALUES ('PARANAVAÍ','1');
SELECT * FROM cidade;

/** CRIAR 3 TABELAS E INSERCOES **/

CREATE TABLE funcionario(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(255) NOT NULL UNIQUE
,cpf VARCHAR(15) NOT NULL UNIQUE
,telefone VARCHAR(10) NOT NULL
);

INSERT INTO funcionario (nome,cpf,telefone)
VALUES ('JOSÉ','123.456.789-10','4002-8922');
SELECT * FROM funcionario;