CREATE DATABASE jose_servicos; /**CRIAR A BASE DE DADOS**/
USE jose_servicos; /**EXECUTAR A BASE DE DADOS**/
DROP DATABASE jose_servicos; /**ELIMINAR A BASE DE DADOS SELECIONADA**/
DROP DATABASE IF EXISTS misael_servicos; /**ELIMINAR A BASE DE DADOS CONDICIONAL**/
CREATE DATABASE misael_servicos; /**CRIAR A BASE DE DADOS NOVAMENTE APÓS DROP CONDICIONAL**/
USE misael_servicos; /**EXECUTAR A BASE DE DADOS**/
CREATE TABLE misael_serviços (
id INT NOT NULL PRIMARY KEY
,nome VARCHAR (255) NOT NULL UNIQUE
,sigla_pais CHAR (2) NOT NULL UNIQUE
,ativar CHAR DEFAULT 'Y' NOT NULL
,CHECK (ativar IN ('Y','Z'))
); /**CRIAR TABELA DE DADOS**/
